### ISSUE TITLE
Coil Whine

### ISSUE THREAD

**Issue by mrdei** [DMNerd/Hackintosh#2]
Hi there.
I have used your project to make my own hackintosh and have been successful.
There is only one thing that bothers you, there is a coil whine on the mobo near the processor.
This is normal? Does it happen to your PC?

**Comment by DMNerd** [comment]
This has no way to cause hardware issues, so it is not relevant to this repo. Coil whine is normal in most cases but you should still look into it yourself as I have no way of diagnosing hardware
