### ISSUE TITLE
Mismatch in config.plist and OpenCore.efi

### ISSUE THREAD

**Issue by Prindle19** [DMNerd/Hackintosh#3]
Hi, i have an identical setup, but, getting errors with this config because (I think) the config.plist and OpenCore.efi are mismatched. 

Do you have an updated confi.plist for your OpenCore 0.7.9 ?

**Comment by DMNerd** [comment]
I do in my private repo. I will update it for you :)

**Comment by DMNerd** [comment]
Solved :)

**Comment by Prindle19** [comment]
Thank you!
